openapi: 3.0.0
info:
  title: API
  version: '1.0'
  description: 'This API represents all of the endpoints that are available for use within the AIMS system. '
  contact:
    name: Adam
servers:
  - description: localhost
    url: 'http://localhost:5000/api/v1'
paths:
  /users:
    get:
      summary: Retrieve Users
      tags:
        - users
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                  required:
                    - id
      operationId: get-users
      description: By default will get all users that current user has access to. Can also be filtered and limited.
      parameters:
        - schema:
            type: string
          in: header
          name: x-access-token
          description: JWT provided by server
          required: true
    post:
      summary: Create User
      operationId: post-users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  firstName:
                    type: string
                required:
                  - firstName
      description: Creates a new user profile
      parameters:
        - schema:
            type: string
          in: header
          name: x-access-token
          description: JWT provided by server
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
              required:
                - firstName
      tags:
        - users
  /credentials/current:
    get:
      summary: Retrieve current user credentials
      tags:
        - credentials
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  username:
                    type: string
                  isAdmin:
                    type: boolean
                  isEmployee:
                    type: boolean
                  isCoach:
                    type: boolean
                  isAthlete:
                    type: boolean
                required:
                  - email
                  - username
                  - isAdmin
                  - isEmployee
                  - isCoach
                  - isAthlete
              examples:
                success:
                  value:
                    email: test@test.com
                    username: test
                    isAdmin: true
                    isEmployee: true
                    isCoach: true
                    isAthlete: true
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
              examples:
                bad token:
                  value: Invalid token.
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: string
              examples:
                no token:
                  value: Access denied. No token provided.
      operationId: get-credentials
      parameters:
        - schema:
            type: string
          in: header
          name: authorization
          description: Saved as HttpOnly cookie from server
          required: true
    parameters: []
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
      required:
        - id
        - firstName
        - lastName
      description: Contains the basic contents of a user profile.
      x-tags:
        - users
